# YOLOv8 configuration file for COCO datasets with 1 class ('person')

# Dataset
train: coco/train2017.txt  # Path to your training image list
val: coco/val2017.txt  # Path to your validation image list

# Classes
nc: 1  # Number of classes
names: [ 'person' ]  # Class names

# Model
depth_multiple: 0.33  # Model depth multiple
width_multiple: 0.50  # Model width multiple

# Parameters
img: 640  # Input image size
rect: 0  # Rectangular training

# Training
epochs: 3  # Number of training epochs
batch_size: 16  # Batch size
subdivisions: 64  # Subdivisions
adam: 0.0001  # Adam optimizer learning rate
momentum: 0.937  # Momentum
weight_decay: 0.0005  # Weight decay
iou_t: 0.20  # IoU training threshold
lr0: 0.01  # Initial learning rate
lrf: 0.0001  # Final learning rate

# YOLOv8 Architecture
anchors:
  - [ 10, 13, 16, 30, 33, 23 ]
  - [ 30, 61, 62, 45, 59, 119 ]
  - [ 116, 90, 156, 198, 373, 326 ]
